default: &default
  adapter: postgresql
  encoding: unicode
  pool: 50
  host: 127.0.0.1
  username: postgres
  password: postgres


development:
  <<: *default
  database: myblog_development

test:
  <<: *default
  database: myblog_test

production:
  <<: *default
  database: myblog_production
